version: "3.8"

services:
  wprs-forecast:
      container_name: wprs-forecast
      build:
        context: ./
        dockerfile: Dockerfile
      environment:
        DATABASE_URL: ${DATABASE_URL}
        SUBMIT_RATE_LIMIT: ${SUBMIT_RATE_LIMIT}

      restart: always
      ports:
        - 3000:3000
      depends_on:
        - redis
      labels:
        traefik.enable: true
        traefik.http.routers.wprs-forecast.rule: "Host(`${TRAEFIK_DOMAIN}`) || Host(`www.wprs-forecast.org`)"
        traefik.http.routers.wprs-forecast.entrypoints: websecure
        traefik.http.routers.wprs-forecast.tls.certresolver: myresolver
        traefik.http.routers.wprs-forecast.priority: 100
        traefik.port: 3000
        traefik.docker.network: traefik

  redis:
    image: redis:6-alpine3.17
    restart: always
    command: redis-server --save 60 1 --loglevel warning 
    volumes: 
      - cache:/data

networks:
  default:
    external:
      name: traefik

volumes:
  cache:
    driver: local

  
