version: "3.8"

services:
  wprs-forecast:
    container_name: wprs-forecast
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}

    restart: always
    ports:
      - 3000:3000
    depends_on:
      - redis
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.wprs-forecast.rule: "Host(`${TRAEFIK_DOMAIN}`) || Host(`www.wprs-forecast.org`)"
      traefik.http.routers.wprs-forecast.entrypoints: websecure
      traefik.http.routers.wprs-forecast.tls.certresolver: myresolver
      traefik.http.routers.wprs-forecast.priority: 100
      traefik.port: 3000
      traefik.docker.network: traefik
  db:
    image: postgres:16-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - wprs-forecast-db:/var/lib/postgresql/data
    ports:
      - 5433:5432

  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
      args:
        CLOUDFLARE_ACCESS_KEY_ID: ${CLOUDFLARE_ACCESS_KEY_ID}
        CLOUDFLARE_SECRET_ACCESS_KEY: ${CLOUDFLARE_SECRET_ACCESS_KEY}
        CLOUDFLARE_R2_ENDPOINT: ${CLOUDFLARE_R2_ENDPOINT}
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data

networks:
  default:
    name: traefik
    external: true

volumes:
  wprs-forecast-db:
  cache:
    driver: local
