services:
  wprs-forecast:
    container_name: wprs-forecast
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    restart: always
