name: Deploy WPRS-Forecast
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login via SSH, pull changes from "main", build docker images and print the log
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~/wprs-forecast
            git pull
            docker compose up -d --build
            docker logs -n 10 wprs-forecast
            docker image prune -a -f
